export const movies = [
  { id: 1, name: "Inception", type: "Movie", year: 2010, image: "https://image.tmdb.org/t/p/w500/qmDpIHrmpJINaRKAfWQfftjCdyi.jpg", video: "https://www.youtube.com/embed/YoHD9XEInc0" },
  { id: 2, name: "The Dark Knight", type: "Movie", year: 2008, image: "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg", video: "https://www.youtube.com/embed/EXeTwQWrcwY" },
  { id: 3, name: "Interstellar", type: "Movie", year: 2014, image: "https://www.youtube.com/embed/zSWdZVtXT7E" },
  { id: 4, name: "Titanic", type: "Movie", year: 1997, image: "https://image.tmdb.org/t/p/w500/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg", video: "https://www.youtube.com/embed/kVrqfYjkTdQ" },
  { id: 5, name: "Avatar", type: "Movie", year: 2009, image: "https://image.tmdb.org/t/p/w500/jRXYjXNq0Cs2TcJjLkki24MLp7u.jpg", video: "https://www.youtube.com/embed/5PSNL1qE6VY" },
  { id: 6, name: "Avengers: Endgame", type: "Movie", year: 2019, image: "https://image.tmdb.org/t/p/w500/or06FN3Dka5tukK1e9sl16pB3iy.jpg", video: "https://www.youtube.com/embed/TcMBFSGVi1c" },
  { id: 7, name: "Joker", type: "Movie", year: 2019, image: "https://image.tmdb.org/t/p/w500/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg", video: "https://www.youtube.com/embed/zAGVQLHvwOY" },
  { id: 8, name: "Parasite", type: "Movie", year: 2019, image: "https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg", video: "https://www.youtube.com/embed/SEUXfv87Wpk" },
  { id: 9, name: "The Shawshank Redemption", type: "Movie", year: 1994, image: "https://image.tmdb.org/t/p/w500/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg", video: "https://www.youtube.com/embed/6hB3S9bIaco" },
  { id: 10, name: "Forrest Gump", type: "Movie", year: 1994, image: "https://image.tmdb.org/t/p/w500/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg", video: "https://www.youtube.com/embed/bLvqoHBptjg" },

  { id: 11, name: "Gladiator", type: "Movie", year: 2000, image: "https://image.tmdb.org/t/p/w500/ty8TGRuvJLPUmAR1H1nRIsgwvim.jpg", video: "https://www.youtube.com/embed/owK1qxDselE" },
  { id: 12, name: "The Matrix", type: "Movie", year: 1999, image: "https://image.tmdb.org/t/p/w500/aOIuZAjPaRIE6CMzbazvcHuHXDc.jpg", video: "https://www.youtube.com/embed/vKQi3bBA1y8" },
  { id: 13, name: "The Lion King", type: "Movie", year: 1994, image: "https://image.tmdb.org/t/p/w500/2bXbqYdUdNVa8VIWXVfclP2ICtT.jpg", video: "https://www.youtube.com/embed/4sj1MT05lAA" },
  { id: 14, name: "The Godfather", type: "Movie", year: 1972, image: "https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsRolD1fZdja1.jpg", video: "https://www.youtube.com/embed/sY1S34973zA" },
  { id: 15, name: "The Prestige", type: "Movie", year: 2006, image: "https://image.tmdb.org/t/p/w500/5MXyQfz8xUP3dIFPTubhTsbFY6N.jpg", video: "https://www.youtube.com/embed/o4gHCmTQDVI" },
  { id: 16, name: "The Departed", type: "Movie", year: 2006, image: "https://image.tmdb.org/t/p/w500/nT97ifVT2J1yMQmeq20Qblg61T.jpg", video: "https://www.youtube.com/embed/iojhqm0JTW4" },
  { id: 17, name: "Whiplash", type: "Movie", year: 2014, image: "https://image.tmdb.org/t/p/w500/lIv1QinFqz4dlp5U4lQ6HaiskOZ.jpg", video: "https://www.youtube.com/embed/7d_jQycdQGo" },
  { id: 18, name: "Dune", type: "Movie", year: 2021, image: "https://image.tmdb.org/t/p/w500/d5NXSklXo0qyIYkgV94XAgMIckC.jpg", video: "https://www.youtube.com/embed/8g18jFHCLXk" },
  { id: 19, name: "The Batman", type: "Movie", year: 2022, image: "https://image.tmdb.org/t/p/w500/74xTEgt7R36Fpooo50r9T25onhq.jpg", video: "https://www.youtube.com/embed/mqqft2x_Aa4" },
  { id: 20, name: "Oppenheimer", type: "Movie", year: 2023, image: "https://image.tmdb.org/t/p/w500/ptpr0kGAckfQkJeJIt8st5dglvd.jpg", video: "https://www.youtube.com/embed/uYPbbksJxIg" },

  { id: 21, name: "Breaking Bad", type: "TV Show", year: 2008, image: "https://image.tmdb.org/t/p/w500/ggFHVNu6YYI5L9pCfOacjizRGt.jpg", video: "https://www.youtube.com/embed/HhesaQXLuRY" },
  { id: 22, name: "Game of Thrones", type: "TV Show", year: 2011, image: "https://image.tmdb.org/t/p/w500/u3bZgnGQ9T01sWNhyveQz0wH0Hl.jpg", video: "https://www.youtube.com/embed/KPLWWIOCOOQ" },
  { id: 23, name: "Stranger Things", type: "TV Show", year: 2016, image: "https://image.tmdb.org/t/p/w500/49WJfeN0moxb9IPfGn8AIqMGskD.jpg", video: "https://www.youtube.com/embed/b9EkMc79ZSU" },
  { id: 24, name: "The Witcher", type: "TV Show", year: 2019, image: "https://image.tmdb.org/t/p/w500/zrPpUlehQaBf8YX2NrVrKK8IEpf.jpg", video: "https://www.youtube.com/embed/ndl1W4ltcmg" },
  { id: 25, name: "The Mandalorian", type: "TV Show", year: 2019, image: "https://image.tmdb.org/t/p/w500/sWgBv7LV2PRoQgkxwlibdGXKz1S.jpg", video: "https://www.youtube.com/embed/aOC8E8z_ifw" },

  { id: 26, name: "Friends", type: "TV Show", year: 1994, image: "https://image.tmdb.org/t/p/w500/f496cm9enuEsZkSPzCwnTESEK5s.jpg", video: "https://www.youtube.com/embed/hDNNmeeJs1Q" },
  { id: 27, name: "The Office", type: "TV Show", year: 2005, image: "https://image.tmdb.org/t/p/w500/qWnJzyZhyy74gjpSjIXWmuk0ifX.jpg", video: "https://www.youtube.com/embed/Vmb1tqYqyII" },
  { id: 28, name: "Sherlock", type: "TV Show", year: 2010, image: "https://image.tmdb.org/t/p/w500/7WTsnHkbA0FaG6R9twfFde0I9hl.jpg", video: "https://www.youtube.com/embed/xK7S9mrFWL4" },
  { id: 29, name: "Loki", type: "TV Show", year: 2021, image: "https://image.tmdb.org/t/p/w500/kEl2t3OhXc3Zb9FBh1AuYzRTgZp.jpg", video: "https://www.youtube.com/embed/nW948Va-l10" },
  { id: 30, name: "Wednesday", type: "TV Show", year: 2022, image: "https://image.tmdb.org/t/p/w500/9PFonBhy4cQy7Jz20NpMygczOkv.jpg", video: "https://www.youtube.com/embed/Di310WS8zLk" },

  { id: 31, name: "Peaky Blinders", type: "TV Show", year: 2013, image: "https://image.tmdb.org/t/p/w500/vUUqzWa2LnHIVqkaKVlVGkVcZIW.jpg", video: "https://www.youtube.com/embed/oVzVdvGIC7U" },
  { id: 32, name: "Money Heist", type: "TV Show", year: 2017, image: "https://image.tmdb.org/t/p/w500/reEMJA1uzscCbkpeRJeTT2bjqUp.jpg", video: "https://www.youtube.com/embed/_InqQJRqGW4" },
  { id: 33, name: "The Boys", type: "TV Show", year: 2019, image: "https://image.tmdb.org/t/p/w500/stTEycfG9928HYGEISBFaG1ngjM.jpg", video: "https://www.youtube.com/embed/M1bhOaLV4FU" },
  { id: 34, name: "Dark", type: "TV Show", year: 2017, image: "https://image.tmdb.org/t/p/w500/5LoUoZtI3Yg8hV5ZfSEaYzB1Vyt.jpg", video: "https://www.youtube.com/embed/rrwycJ08PSA" },
  { id: 35, name: "House of the Dragon", type: "TV Show", year: 2022, image: "https://image.tmdb.org/t/p/w500/z2yahl2uefxDCl0nogcRBstwruJ.jpg", video: "https://www.youtube.com/embed/DotnJ7tTA34" },

  { id: 36, name: "The Crown", type: "TV Show", year: 2016, image: "https://image.tmdb.org/t/p/w500/1M876KPjulVwppEpldhdc8V4o68.jpg", video: "https://www.youtube.com/embed/JWtnJjn6ng0" },
  { id: 37, name: "Black Mirror", type: "TV Show", year: 2011, image: "https://image.tmdb.org/t/p/w500/7PRddO7z7mcPi21nZTCMGShAyy1.jpg", video: "https://www.youtube.com/embed/jDiYGjp5iFg" },
  { id: 38, name: "Narcos", type: "TV Show", year: 2015, image: "https://image.tmdb.org/t/p/w500/rTmal9fDbwh5F0waol2hq35U4ah.jpg", video: "https://www.youtube.com/embed/U7elNhHwgBU" },
  { id: 39, name: "The Walking Dead", type: "TV Show", year: 2010, image: "https://image.tmdb.org/t/p/w500/reKs8y4mPwPkZG99ZpbKRhBPKsX.jpg", video: "https://www.youtube.com/embed/R1v0uFms68U" },
  { id: 40, name: "Better Call Saul", type: "TV Show", year: 2015, image: "https://image.tmdb.org/t/p/w500/fC2HDm5t0kHl7hWnZyH9C9P9n9Q.jpg", video: "https://www.youtube.com/embed/HN4oydykJFc" }
];
