export const movies = [
  { id: 1, name: "Inception", type: "Movie", year: 2010, image: "https://image.tmdb.org/t/p/w500/qmDpIHrmpJINaRKAfWQfftjCdyi.jpg" },
  { id: 2, name: "The Dark Knight", type: "Movie", year: 2008, image: "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg" },
  { id: 3, name: "Interstellar", type: "Movie", year: 2014, image: "https://image.tmdb.org/t/p/w500/rAiYTfKGqDCRIIqo664sY9XZIvQ.jpg" },
  { id: 4, name: "Titanic", type: "Movie", year: 1997, image: "https://image.tmdb.org/t/p/w500/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg" },
  { id: 5, name: "Avatar", type: "Movie", year: 2009, image: "https://image.tmdb.org/t/p/w500/jRXYjXNq0Cs2TcJjLkki24MLp7u.jpg" },
  { id: 6, name: "Avengers: Endgame", type: "Movie", year: 2019, image: "https://image.tmdb.org/t/p/w500/or06FN3Dka5tukK1e9sl16pB3iy.jpg" },
  { id: 7, name: "Joker", type: "Movie", year: 2019, image: "https://image.tmdb.org/t/p/w500/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg" },
  { id: 8, name: "Parasite", type: "Movie", year: 2019, image: "https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg" },
  { id: 9, name: "The Shawshank Redemption", type: "Movie", year: 1994, image: "https://image.tmdb.org/t/p/w500/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg" },
  { id: 10, name: "Forrest Gump", type: "Movie", year: 1994, image: "https://image.tmdb.org/t/p/w500/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg" },

  { id: 11, name: "Gladiator", type: "Movie", year: 2000, image: "https://image.tmdb.org/t/p/w500/ty8TGRuvJLPUmAR1H1nRIsgwvim.jpg" },
  { id: 12, name: "The Matrix", type: "Movie", year: 1999, image: "https://image.tmdb.org/t/p/w500/aOIuZAjPaRIE6CMzbazvcHuHXDc.jpg" },
  { id: 13, name: "The Lion King", type: "Movie", year: 1994, image: "https://image.tmdb.org/t/p/w500/2bXbqYdUdNVa8VIWXVfclP2ICtT.jpg" },
  { id: 14, name: "The Godfather", type: "Movie", year: 1972, image: "https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsRolD1fZdja1.jpg" },
  { id: 15, name: "The Prestige", type: "Movie", year: 2006, image: "https://image.tmdb.org/t/p/w500/5MXyQfz8xUP3dIFPTubhTsbFY6N.jpg" },
  { id: 16, name: "The Departed", type: "Movie", year: 2006, image: "https://image.tmdb.org/t/p/w500/nT97ifVT2J1yMQmeq20Qblg61T.jpg" },
  { id: 17, name: "Whiplash", type: "Movie", year: 2014, image: "https://image.tmdb.org/t/p/w500/lIv1QinFqz4dlp5U4lQ6HaiskOZ.jpg" },
  { id: 18, name: "Dune", type: "Movie", year: 2021, image: "https://image.tmdb.org/t/p/w500/d5NXSklXo0qyIYkgV94XAgMIckC.jpg" },
  { id: 19, name: "The Batman", type: "Movie", year: 2022, image: "https://image.tmdb.org/t/p/w500/74xTEgt7R36Fpooo50r9T25onhq.jpg" },
  { id: 20, name: "Oppenheimer", type: "Movie", year: 2023, image: "https://image.tmdb.org/t/p/w500/ptpr0kGAckfQkJeJIt8st5dglvd.jpg" },

  { id: 21, name: "Breaking Bad", type: "TV Show", year: 2008, image: "https://image.tmdb.org/t/p/w500/ggFHVNu6YYI5L9pCfOacjizRGt.jpg" },
  { id: 22, name: "Game of Thrones", type: "TV Show", year: 2011, image: "https://image.tmdb.org/t/p/w500/u3bZgnGQ9T01sWNhyveQz0wH0Hl.jpg" },
  { id: 23, name: "Stranger Things", type: "TV Show", year: 2016, image: "https://image.tmdb.org/t/p/w500/49WJfeN0moxb9IPfGn8AIqMGskD.jpg" },
  { id: 24, name: "The Witcher", type: "TV Show", year: 2019, image: "https://image.tmdb.org/t/p/w500/zrPpUlehQaBf8YX2NrVrKK8IEpf.jpg" },
  { id: 25, name: "The Mandalorian", type: "TV Show", year: 2019, image: "https://image.tmdb.org/t/p/w500/sWgBv7LV2PRoQgkxwlibdGXKz1S.jpg" },
  { id: 26, name: "Friends", type: "TV Show", year: 1994, image: "https://image.tmdb.org/t/p/w500/f496cm9enuEsZkSPzCwnTESEK5s.jpg" },
  { id: 27, name: "The Office", type: "TV Show", year: 2005, image: "https://image.tmdb.org/t/p/w500/qWnJzyZhyy74gjpSjIXWmuk0ifX.jpg" },
  { id: 28, name: "Sherlock", type: "TV Show", year: 2010, image: "https://image.tmdb.org/t/p/w500/7WTsnHkbA0FaG6R9twfFde0I9hl.jpg" },
  { id: 29, name: "Loki", type: "TV Show", year: 2021, image: "https://image.tmdb.org/t/p/w500/kEl2t3OhXc3Zb9FBh1AuYzRTgZp.jpg" },
  { id: 30, name: "Wednesday", type: "TV Show", year: 2022, image: "https://image.tmdb.org/t/p/w500/9PFonBhy4cQy7Jz20NpMygczOkv.jpg" },

  
  { id: 31, name: "Peaky Blinders", type: "TV Show", year: 2013, image: "https://image.tmdb.org/t/p/w500/vUUqzWa2LnHIVqkaKVlVGkVcZIW.jpg" },
  { id: 32, name: "Money Heist", type: "TV Show", year: 2017, image: "https://image.tmdb.org/t/p/w500/reEMJA1uzscCbkpeRJeTT2bjqUp.jpg" },
  { id: 33, name: "The Boys", type: "TV Show", year: 2019, image: "https://image.tmdb.org/t/p/w500/stTEycfG9928HYGEISBFaG1ngjM.jpg" },
  { id: 34, name: "Dark", type: "TV Show", year: 2017, image: "https://image.tmdb.org/t/p/w500/5LoUoZtI3Yg8hV5ZfSEaYzB1Vyt.jpg" },
  { id: 35, name: "House of the Dragon", type: "TV Show", year: 2022, image: "https://image.tmdb.org/t/p/w500/z2yahl2uefxDCl0nogcRBstwruJ.jpg" },
  { id: 36, name: "The Crown", type: "TV Show", year: 2016, image: "https://image.tmdb.org/t/p/w500/1M876KPjulVwppEpldhdc8V4o68.jpg" },
  { id: 37, name: "Black Mirror", type: "TV Show", year: 2011, image: "https://image.tmdb.org/t/p/w500/7PRddO7z7mcPi21nZTCMGShAyy1.jpg" },
  { id: 38, name: "Narcos", type: "TV Show", year: 2015, image: "https://image.tmdb.org/t/p/w500/rTmal9fDbwh5F0waol2hq35U4ah.jpg" },
  { id: 39, name: "The Walking Dead", type: "TV Show", year: 2010, image: "https://image.tmdb.org/t/p/w500/reKs8y4mPwPkZG99ZpbKRhBPKsX.jpg" },
  { id: 40, name: "Better Call Saul", type: "TV Show", year: 2015, image: "https://image.tmdb.org/t/p/w500/fC2HDm5t0kHl7hWnZyH9C9P9n9Q.jpg" }]